module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    colors: {
      white: "#FFFFFF",
      ash: "#737373",
      gray: "#F3F3F3",
      black: "#000000",
      "black-opacity": "#00000088",
      darkgray: "#CCCCCC",
      skeleton: "#e7e7e7",
      red: "#FF0000",
      skyblue: "#067DB6",
      "font-blue": "#1D3449",
      "bs-blue": "#4F86BA",
      "bs-light": "#F3F4F6",
      "text-header": "#393A41",
      "text-para": "#9294A0",
      "border-light": "#BEBEC6",
      "border-blue": "#0B90E2",
      transparent: "FFFFFF00",
      inherit: "inherit",
      lightgray: "#00000035",
      lightash: "#f0f0f0",
      navlink: "#e5dfd9",
    },
    fontFamily: {
      // sans: ["Graphik", "sans-serif"],
      // serif: ["Merriweather", "serif"],
    },
    extend: {},
  },
  plugins: [require("@tailwindcss/forms")],
};
